FROM python:3.12-slim

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential librdkafka-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire backend folder into /app/backend
COPY . ./backend/

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

# The CMD will be overridden by docker-compose for each service
CMD ["python"]
