global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "sentinelx-api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]   # internal container port
    metrics_path: /metrics

  - job_name: "sentinelx-ingestion"
    static_configs:
      - targets: ["ingestion-service:8001"]
    metrics_path: /metrics

  - job_name: "sentinelx-auth"
    static_configs:
      - targets: ["auth-service:8002"]
    metrics_path: /metrics

  - job_name: "sentinelx-alerts"
    static_configs:
      - targets: ["alert-service:8004"]
    metrics_path: /metrics

  - job_name: "sentinelx-search"
    static_configs:
      - targets: ["search-service:8005"]
    metrics_path: /metrics

  - job_name: "sentinelx-ws"
    static_configs:
      - targets: ["websocket-gateway:8006"]
    metrics_path: /metrics

  - job_name: "sentinelx-ai"
    static_configs:
      - targets: ["ai-service:8007"]
    metrics_path: /metrics

  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9101"]
